# Generated by Django 5.1.6 on 2025-02-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='machinedata',
            new_name='machinedata_timesta_635c09_idx',
            old_name='monitoring__timesta_4e59ba_idx',
        ),
        migrations.RenameIndex(
            model_name='machinedata',
            new_name='machinedata_data_it_f49a1e_idx',
            old_name='monitoring__data_it_e4922d_idx',
        ),
        migrations.AlterModelTable(
            name='machinedata',
            table='machinedata',
        ),
    ]
