version: '3.8'

services:

  factorydash.dev:
    container_name: factorydash.dev
    image: factorydash.dev:latest
    restart: always
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /factorydash/app/factorydash
    volumes:
      - .:/factorydash
      - logs_volume:/factorydash/app/factorydash/logs  # Persist logs outside the container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://factorydash:factorydash@db:5432/factorydash
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/factorydash/app/factorydash
      - PYTHONDONTWRITEBYTECODE 1
      - PYTHONUNBUFFERED 1
      - DJANGO_SETTINGS_MODULE=factorydash.settings
    depends_on:
      - db  # Ensure db is started before factorydash.dev
      - redis # Ensure redis is started before factorydash.dev

  celery_worker:
    container_name: factorydash.celery_worker.dev
    image: factorydash.dev:latest
    restart: always
    command: celery -A factorydash worker --loglevel=info
    volumes:
      - .:/factorydash
    depends_on:
      - factorydash.dev
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/factorydash/app/factorydash
      - DJANGO_SETTINGS_MODULE=factorydash.settings      

  celery_beat:
    container_name: factorydash.celery_beat.dev
    image: factorydash.dev:latest
    restart: always
    command: celery -A factorydash beat --loglevel=info
    volumes:
      - .:/factorydash
    depends_on:
      - factorydash.dev
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - PYTHONPATH=/factorydash/app/factorydash
      - DJANGO_SETTINGS_MODULE=factorydash.settings      

  db:
    container_name: factorydash.postgres.dev
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: factorydash
      POSTGRES_PASSWORD: factorydash
      POSTGRES_DB: factorydash
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: factorydash.redis.dev
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  logs_volume:


