services:

  factorydash:
    container_name: factorydash
    image: factorydash:latest    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"    
    environment:
      - DATABASE_URL=postgres://factorydash:factorydash@postgres:5432/factorydash
      - CELERY_BROKER_URL=redis://redis:6379/0 
      - DJANGO_SETTINGS_MODULE=factorydash.settings
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: factorydash.postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: factorydash
      POSTGRES_PASSWORD: factorydash
      POSTGRES_DB: factorydash
    ports:
      - "5432:5432"

  redis:
    container_name: factorydash.redis
    image: redis:latest    
    ports:
      - "6379:6379"



