version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: factorydash
      POSTGRES_USER: factorydash
      POSTGRES_PASSWORD: factorydash
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"