services:

  factorydash:
    container_name: factorydash
    image: factorydash:latest
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.factorydash.test
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: factorydash.postgres
    image: postgres:latest
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - factorydash_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.postgres.test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "factorydash"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: factorydash.redis
    image: redis:latest
    restart: no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  factorydash_postgres_data:
    name: factorydash_postgres_data


