# Generated by Django 5.1.6 on 2025-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('Events', 'Events'), ('Samples', 'Samples')], max_length=10)),
                ('data_item_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='monitoring__timesta_4e59ba_idx'), models.Index(fields=['data_item_id'], name='monitoring__data_it_e4922d_idx')],
            },
        ),
    ]
