# Generated by Django 5.1.7 on 2025-03-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_monitoring__timesta_4e59ba_idx_machinedata_timesta_635c09_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='machinedata',
            name='machinedata_timesta_635c09_idx',
        ),
        migrations.RemoveIndex(
            model_name='machinedata',
            name='machinedata_data_it_f49a1e_idx',
        ),
        migrations.RenameField(
            model_name='machinedata',
            old_name='data_item_id',
            new_name='machine_id',
        ),
        migrations.RemoveField(
            model_name='machinedata',
            name='data_type',
        ),
        migrations.AddIndex(
            model_name='machinedata',
            index=models.Index(fields=['timestamp', 'machine_id', 'name'], name='machinedata_timesta_ae1cdf_idx'),
        ),
    ]
