name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://factorydash:factorydash@postgres:5432/factorydash
      CELERY_BROKER_URL: redis://factorydash.redis:6379/0
      CELERY_RESULT_BACKEND: redis://factorydash.redis:6379/0
      DJANGO_SETTINGS_MODULE: factorydash.settings

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker Compose V2
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Remove Existing Containers
        run: |
          docker rm -f factorydash.postgres || true
          docker rm -f factorydash.redis || true

      - name: Start services
        run: docker compose up -d

      - name: Check PostgreSQL Logs
        run: docker logs factorydash.postgres

      - name: Build Docker container
        run: |
          docker build -t factorydash .

      - name: Remove existing Docker container if exists
        run: |
          docker rm -f factorydash || true

      - name: Run Docker container
        run: |
          docker run -d --name factorydash -p 8000:8000 factorydash

      - name: Wait for Docker container to be ready
        run: |
          sleep 10 # Wait for the container to be fully up and running

      - name: Wait for PostgreSQL to be ready inside Docker
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..30}; do  # Try for up to 60 seconds
            if docker exec factorydash.postgres pg_isready -U factorydash; then
              echo "PostgreSQL is ready!"
              exit 0
            fi
            echo "PostgreSQL not ready yet, retrying in 2s..."
            sleep 2
          done
          echo "PostgreSQL did not become ready in time"
          docker logs factorydash.postgres  # Show PostgreSQL logs for debugging
          exit 1  # Fail the pipeline if PostgreSQL doesn't start

      - name: Check PostgreSQL Service Status
        run: docker exec -it factorydash.postgres bash -c "PGUSER=factorydash pg_isready -h factorydash.postgres -p 5432"

      - name: Run migrations in Docker container
        run: |
          until docker exec factorydash.postgres pg_isready -h factorydash.postgres -p 5432 -U factorydash; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done
          echo "PostgreSQL is ready, running migrations..."
          docker exec -it factorydash bash -c "cd /factorydash/app/factorydash && python manage.py migrate"

      - name: Run tests in Docker container
        run: |
          docker exec -it factorydash bash -c "cd /factorydash/app/factorydash && python manage.py test"

      - name: Run pytest in Docker container
        run: |
          docker exec -it factorydash bash -c "cd /factorydash/app/factorydash && pytest"

      - name: Run Celery worker
        run: |
          docker exec -d factorydash celery -A factorydash worker --loglevel=info

      - name: Run Celery beat
        run: |
          docker exec -d factorydash celery -A factorydash beat --loglevel=info

      - name: Check Docker container status
        run: |
          docker ps -a