name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME || env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD || env.DOCKER_PASSWORD }}

      - name: Remove Existing Containers
        run: |
          docker rm -f factorydash.postgres || true
          docker rm -f factorydash.redis || true
          docker rm -f factorydash || true

      - name: Start services
        run: docker compose up -d      

      - name: Build Docker container
        run: |
          docker build -t factorydash .      

      - name: Run pytest in Docker container
        run: |
          docker exec -it factorydash bash -c "cd /factorydash/app/factorydash && pytest"

      - name: Check the integrity of the Django project in Docker container
        run: |
          docker exec -it factorydash bash -c "cd /factorydash/app/factorydash && python manage.py check"          

      - name: Run migrations in Docker container
        run: |
          docker exec -it factorydash bash -c "cd /factorydash/app/factorydash && python manage.py migrate"

      - name: Run Celery worker
        run: |
          docker exec -d factorydash celery -A factorydash worker --loglevel=info

      - name: Run Celery beat
        run: |
          docker exec -d factorydash celery -A factorydash beat --loglevel=info

      
