name: Deploy to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django

      - name: Run Django Check
        env:
          DJANGO_SETTINGS_MODULE: factorydash.settings_test
          DATABASE_URL: sqlite:///test.db
          PYTHONPATH: app/factorydash
        run: |
          python app/factorydash/manage.py check --settings=factorydash.settings_test

      - name: Run Pytest
        env:
          DJANGO_SETTINGS_MODULE: factorydash.settings_test
          DATABASE_URL: sqlite:///test.db
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
          LOAD_NIST_DATA_SCHEDULE_SECONDS: 10
          DATA_RETENTION_DAYS: 2
          PYTHONPATH: app/factorydash
        run: |
          pytest --verbose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t franciscoricardodev/factorydash:latest .
          docker tag franciscoricardodev/factorydash:latest franciscoricardodev/factorydash:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push franciscoricardodev/factorydash:latest
          docker push franciscoricardodev/factorydash:${{ github.sha }}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: railway up --service factorydash --environment production